apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: zookeeper-log
  name: zookeeper-log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
