apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: predictor
  name: predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: predictor
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: predictor
    spec:
      containers:
        - env:
            - name: KAFKA_SERVER
              value: kafka:9092
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_SERVER
              value: postgres:5432
            - name: POSTGRES_USER
              value: postgres
            - name: ZOOKEEPER_SERVER
              value: zookeeper:2181
          image: kafka7_predictor
          name: predictor
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
